name: Release Workflow

on:
  create:
    branches:
      - 'release/*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x.x' # You can adjust the version if needed

    - name: Extract version
      run: |
        # Extract version from the branch name (assuming the branch name format is release/x.y.z)
        version=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/release\///')
        echo "Version extracted from branch name: $version"
      id: extract-version

    - name: Build
      run: |
        # Restore dependencies and build the code
        dotnet restore
        dotnet build --configuration Release
    - name: Push
      run: |
        # Find all projects in the repository
        packages=$(find . -name '*.nupkg')

        echo ${{ steps.extract-version.outputs.version }}

        for package in $packages; do
           echo $package
        done
 
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
